### ISSUE TITLE
Hash routing requires trailing slash

### ISSUE THREAD

**Issue by cp-sean** [dievardump/yasp-router#1]
If I define a route like this `<Route path="#welcome">`, it won't match for `site.com/#welcome`, it needs a trailing slash like `site.com/#welcome/`. Is there any way to get it to match for both? Thanks!

**Comment by dievardump** [comment]
Sorry for the late reply, I just saw this now.

I will look at this today or tomorrow

**Comment by dievardump** [comment]
@cp-sean Hi, I pushed a fixed for this behavior. Tests seems to show that it works now, let me know if there is anything else.

**Comment by cp-sean** [comment]
Nice!
